#!/usr/bin/env bash
# Summary: Show the current Ruby version
set -e
[ -n "$GOENV_DEBUG" ] && set -x

if [ -z "$GOENV_VERSION" ]; then
  GOENV_VERSION_FILE="$(goenv-version-file)"
  GOENV_VERSION="$(goenv-version-file-read "$GOENV_VERSION_FILE" || true)"
fi

if [ -z "$GOENV_VERSION" ] || [ "$GOENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${GOENV_ROOT}/versions/${version}" ]
}

if version_exists "$GOENV_VERSION"; then
  echo "$GOENV_VERSION"
elif version_exists "${GOENV_VERSION#ruby-}"; then
  { echo "warning: ignoring extraneous \`ruby-' prefix in version \`${GOENV_VERSION}'"
    echo "         (set by $(goenv-version-origin))"
  } >&2
  echo "${GOENV_VERSION#ruby-}"
else
  echo "goenv: version \`$GOENV_VERSION' is not installed" >&2
  exit 1
fi
