#!/usr/bin/env bash
# Summary: Explain how the current Ruby version is set
set -e
[ -n "$GOENV_DEBUG" ] && set -x

if [ -n "$RBENV_VERSION" ]; then
  echo "RBENV_VERSION environment variable"
else
  goenv-version-file
fi
