#!/usr/bin/env bash
set -e
[ -n "$GOENV_DEBUG" ] && set -x

# Provide goenv completions
if [ "$1" = "--complete" ]; then
  exec goenv-setup --complete
fi

shell="$(basename "${GOENV_SHELL:-$SHELL}")"

# When goenv shell integration is enabled, delegate to goenv-setup,
# then tell the shell to empty its command lookup cache.
goenv-setup

case "$shell" in
fish )
  # no setup support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
