#!/usr/bin/env bash
# Summary: List hook scripts for a given goenv command
# Usage: goenv hooks <command>

set -e
[ -n "$GOENV_DEBUG" ] && set -x

# Provide goenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo setup
  echo which
  exit
fi

GOENV_COMMAND="$1"
if [ -z "$GOENV_COMMAND" ]; then
  goenv-help --usage hooks >&2
  exit 1
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "goenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

realpath() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  echo "$(pwd)/$name"
  cd "$cwd"
}

IFS=: hook_paths=($GOENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$GOENV_COMMAND"/*.bash; do
    echo $(realpath $script)
  done
done
shopt -u nullglob
