#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Golang version
#
# Usage: goenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Golang
# version's `bin' directory is at the front.
#
# For example, if the currently selected Golang version is go1:
#   goenv exec go install
#
# is equivalent to:
#   PATH="$GOENV_ROOT/versions/go1/bin:$PATH" go install

set -e
[ -n "$GOENV_DEBUG" ] && set -x

# Provide goenv completions
if [ "$1" = "--complete" ]; then
  exec goenv shims --short
fi

GOENV_VERSION="$(goenv-version-name)"
RBENV_COMMAND="$1"

if [ -z "$RBENV_COMMAND" ]; then
  goenv-help --usage exec >&2
  exit 1
fi

export GOENV_VERSION
RBENV_COMMAND_PATH="$(goenv-which "$RBENV_COMMAND")"
RBENV_BIN_PATH="${RBENV_COMMAND_PATH%/*}"

OLDIFS="$IFS"
IFS=$'\n' scripts=(`goenv-hooks exec`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

shift 1
if [ "$GOENV_VERSION" != "system" ]; then
  export PATH="${RBENV_BIN_PATH}:${PATH}"
fi
exec -a "$RBENV_COMMAND" "$RBENV_COMMAND_PATH" "$@"
