#!/usr/bin/env bash
# Summary: Display prefix for a Ruby version
# Usage: goenv prefix [<version>]
#
# Displays the directory where a Ruby version is installed. If no
# version is given, `goenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$GOENV_DEBUG" ] && set -x

# Provide goenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec goenv-versions --bare
fi

if [ -n "$1" ]; then
  export GOENV_VERSION="$1"
elif [ -z "$GOENV_VERSION" ]; then
  GOENV_VERSION="$(goenv-version-name)"
fi

if [ "$GOENV_VERSION" = "system" ]; then
  if RUBY_PATH="$(goenv-which ruby 2>/dev/null)"; then
    RUBY_PATH="${RUBY_PATH%/*}"
    echo "${RUBY_PATH%/bin}"
    exit
  else
    echo "goenv: system version not found in PATH" >&2
    exit 1
  fi
fi

RBENV_PREFIX_PATH="${GOENV_ROOT}/versions/${GOENV_VERSION}"
if [ ! -d "$RBENV_PREFIX_PATH" ]; then
  echo "goenv: version \`${GOENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$RBENV_PREFIX_PATH"
