#!/usr/bin/env bash
#
# Summary: Set or show the global Golang version
#
# Usage: goenv global <version>
#
# Sets the global Golang version. You can override the global version at
# any time by setting a directory-specific version with `goenv local'
# or by setting the `GOENV_VERSION' environment variable.
#
# <version> should be a string matching a Golang version known to goenv.
# The special version string `system' will use your default system Golang.
# Run `goenv versions' for a list of available Golang versions.

set -e
[ -n "$GOENV_DEBUG" ] && set -x

# Provide goenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec goenv-versions --bare
fi

GOENV_VERSION="$1"
GOENV_VERSION_FILE="${GOENV_ROOT}/version"

if [ -n "$GOENV_VERSION" ]; then
  goenv-version-file-write "$GOENV_VERSION_FILE" "$GOENV_VERSION"
else
  goenv-version-file-read "$GOENV_VERSION_FILE" ||
  goenv-version-file-read "${GOENV_ROOT}/global" ||
  goenv-version-file-read "${GOENV_ROOT}/default" ||
  echo system
fi
