#!/usr/bin/env bash
# Usage: goenv completions <command> [arg1 arg2...]

set -e
[ -n "$GOENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  goenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "goenv-$COMMAND" || command -v "goenv-sh-$COMMAND")"
if grep -iE "^([#%]|--|//) provide goenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
