#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export GOENV_DEBUG=1
  shift
fi

if [ -n "$GOENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "goenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${GOENV_ROOT}" ]; then
  GOENV_ROOT="${HOME}/.goenv"
else
  GOENV_ROOT="${GOENV_ROOT%/}"
fi
export GOENV_ROOT

if [ -z "${GOENV_DIR}" ]; then
  GOENV_DIR="$(pwd)"
else
  cd "$GOENV_DIR" 2>/dev/null || {
    echo "goenv: cannot change working directory to \`$GOENV_DIR'"
    exit 1
  } >&2
  GOENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export GOENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${GOENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${RBENV_HOOK_PATH}:${GOENV_ROOT}/goenv.d:/usr/local/etc/goenv.d:/etc/goenv.d:/usr/lib/goenv/hooks"
for plugin_hook in "${GOENV_ROOT}/plugins/"*/etc/goenv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export RBENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(goenv---version)\n$(goenv-help)" >&2
  ;;
"-v" )
  exec goenv---version
  ;;
* )
  command_path="$(command -v "goenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "goenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
