#!/usr/bin/env bash
# Summary: Detect the file that sets the current goenv version
set -e
[ -n "$GOENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.ruby-version" ]; then
      echo "${root}/.ruby-version"
      exit
    elif [ -e "${root}/.goenv-version" ]; then
      echo "${root}/.goenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$GOENV_DIR"
[ "$GOENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${GOENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${GOENV_ROOT}/global" ]; then
  echo "${GOENV_ROOT}/global"
elif [ -e "${GOENV_ROOT}/default" ]; then
  echo "${GOENV_ROOT}/default"
else
  echo "$global_version_file"
fi
