#!/usr/bin/env bash
# Summary: Show the current Ruby version
set -e
[ -n "$GOENV_DEBUG" ] && set -x

if [ -z "$RBENV_VERSION" ]; then
  RBENV_VERSION_FILE="$(goenv-version-file)"
  RBENV_VERSION="$(goenv-version-file-read "$RBENV_VERSION_FILE" || true)"
fi

if [ -z "$RBENV_VERSION" ] || [ "$RBENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${GOENV_ROOT}/versions/${version}" ]
}

if version_exists "$RBENV_VERSION"; then
  echo "$RBENV_VERSION"
elif version_exists "${RBENV_VERSION#ruby-}"; then
  { echo "warning: ignoring extraneous \`ruby-' prefix in version \`${RBENV_VERSION}'"
    echo "         (set by $(goenv-version-origin))"
  } >&2
  echo "${RBENV_VERSION#ruby-}"
else
  echo "goenv: version \`$RBENV_VERSION' is not installed" >&2
  exit 1
fi
