#!/usr/bin/env bash
# Summary: Explain how the current Golang version is set
set -e
[ -n "$GOENV_DEBUG" ] && set -x

if [ -n "$GOENV_VERSION" ]; then
  echo "GOENV_VERSION environment variable"
else
  goenv-version-file
fi
