#!/usr/bin/env bash
# Summary: Show the current Golang version and its origin
#
# Shows the currently selected Golang version and how it was
# selected. To obtain only the version string, use `goenv
# version-name'.

set -e
[ -n "$GOENV_DEBUG" ] && set -x

echo "$(goenv-version-name) (set by $(goenv-version-origin))"
