#!/usr/bin/env bash
# Summary: Display prefix for a Golang version
# Usage: goenv prefix [<version>]
#
# Displays the directory where a Golang version is installed. If no
# version is given, `goenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$GOENV_DEBUG" ] && set -x

# Provide goenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec goenv-versions --bare
fi

if [ -n "$1" ]; then
  export GOENV_VERSION="$1"
elif [ -z "$GOENV_VERSION" ]; then
  GOENV_VERSION="$(goenv-version-name)"
fi

if [ "$GOENV_VERSION" = "system" ]; then
  if GO_PATH="$(goenv-which go 2>/dev/null)"; then
    GO_PATH="${GO_PATH%/*}"
    echo "${GO_PATH%/bin}"
    exit
  else
    echo "goenv: system version not found in PATH" >&2
    exit 1
  fi
fi

GO_PREFIX_PATH="${GOENV_ROOT}/versions/${GOENV_VERSION}"
if [ ! -d "$GO_PREFIX_PATH" ]; then
  echo "goenv: version \`${GOENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$GO_PREFIX_PATH"
