#!/usr/bin/env bash
# Usage: goenv version-file-write <file> <version>

set -e
[ -n "$GOENV_DEBUG" ] && set -x

GOENV_VERSION_FILE="$1"
GOENV_VERSION="$2"

if [ -z "$GOENV_VERSION" ] || [ -z "$GOENV_VERSION_FILE" ]; then
  goenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
goenv-prefix "$GOENV_VERSION" >/dev/null

# Write the version out to disk.
echo "$GOENV_VERSION" > "$GOENV_VERSION_FILE"
